{
    "name": "Insilos Intelligent Operations Website",
    "summary": "Production-ready QWeb and Owl website for Insilos",
    "version": "20.0.2.0.0",
    "category": "Website/Website",
    "author": "Insilos",
    "website": "https://insilos.ai",
    "license": "LGPL-3",
    "depends": ["website", "mail", "crm", "marketing_automation", "marketing_automation_crm"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/demo_request_views.xml",
        "views/website_templates.xml",
        "views/home.xml",
        "views/platform_solutions.xml",
        "views/industries.xml",
        "views/resources_about_demo.xml",
        "views/snippets.xml",
        "views/snippets_cinematic.xml",
        "views/showcase_landing.xml",
        "data/marketing_automation_demo.xml",
        "views/website_menu.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "insilos_website/static/src/scss/insilos.scss",
            "insilos_website/static/src/scss/insilos_megamenu.scss",
            "insilos_website/static/src/js/reveal.js",
            "insilos_website/static/src/js/c3ai_interactive.js",
            "insilos_website/static/src/js/insilos_megamenu.js",
            "insilos_website/static/src/components/industry_explorer/industry_explorer.js",
            "insilos_website/static/src/components/industry_explorer/industry_explorer.xml",
            "insilos_website/static/src/components/agent_workflow/agent_workflow.js",
            "insilos_website/static/src/components/agent_workflow/agent_workflow.xml",
        ],
    },
    "images": ["static/description/banner.png"],
    "installable": True,
    "application": True,
}
