{
    "name": "Website Appointment Sale Project",
    "version": "1.0",
    "category": "Services/Appointment",
    "summary": "Automatically set dates on tasks generated by appointments",
    "description": """When a task is generated through a SO itself generated through an appointment, use the appointment dates on the generated task.""",
    "author": "Odoo S.A.",
    "license": "OEEL-1",
    "auto_install": True,
    "depends": ["website_appointment_sale", "sale_project"],
    'data': [
        'views/project_views.xml',
    ],
}
