VERSION = '1.0'

RELATIONS = frozenset({
    'SUPPLIES', 'PURCHASED_FROM', 'SOLD_TO', 'CONTAINS', 'CLASSIFIED_AS',
    'SUBJECT_TO', 'ELIGIBLE_FOR', 'CLAIMS_ORIGIN', 'SUPPORTED_BY',
    'ISSUED_BY', 'ISSUED_TO', 'REFERENCES', 'REQUIRES', 'APPLIES_TO',
    'IMPLEMENTS', 'GUIDES', 'AMENDS', 'REPEALS', 'REPLACES', 'BASED_ON',
    'HAS_PSR', 'HAS_TARIFF', 'HAS_NTM', 'SHIPPED_FROM', 'SHIPPED_TO',
    'CARRIED_BY', 'FORWARDED_BY', 'PACKED_IN', 'BELONGS_TO', 'RELATED_TO',
    'CONTROLLED_BY', 'OWNED_BY', 'AFFECTS',
    'EMITS_GHG', 'MONITORED_BY_CEMS', 'IMPACTS_ENVIRONMENT', 'SUBJECT_TO_CBAM', 'CALCULATED_AS_SCOPE3',
})


def require_relation(code):
    if code not in RELATIONS:
        raise ValueError('Unknown KG relation: %s' % code)
    return code
