FROM docker.io/innoriahub/insilos@sha256:d171235965aa4c8de763918ed95e1e8674e65355c0087492d82227c8bb09cfeb

COPY --chown=insilos:insilos . /app/insilos/apps/insilos_capital_markets_decision_governance/
