{
    'name': 'Audit Reports',
    'summary': 'Create Audit Reports with Knowledge',
    'version': '1.0',
    'depends': [
        'accountant',
        'knowledge',
        'sign',
    ],
    'data': [
        'security/ir.model.access.csv',
        'report/reports.xml',
        'views/audit_report_views.xml',
        'views/knowledge_article_views.xml',
        'views/menuitems.xml',
        'data/ir_attachment_data.xml',
        'data/knowledge_article_template_category_data.xml',
        'data/knowledge_article_template_data.xml',
    ],
    'installable': True,
    'auto_install': True,
    'author': 'Odoo S.A.',
    'license': 'OEEL-1',
    'assets': {
        'web.assets_backend': [
            'accountant_knowledge/static/src/components/**/*',
            'accountant_knowledge/static/src/editor/**/*',
            'accountant_knowledge/static/src/scss/**/*',
            'accountant_knowledge/static/src/views/**/*',
        ],
        'web.assets_frontend': [
            'accountant_knowledge/static/src/editor/embedded_components/core/**/*',
            'accountant_knowledge/static/src/public/**/*',
        ],
        'accountant_knowledge.report_assets': [
            'web/static/lib/bootstrap/scss/_functions.scss',
            'web/static/lib/bootstrap/scss/_mixins.scss',
            'web/static/lib/bootstrap/scss/_variables.scss',
            'web/static/lib/bootstrap/scss/_maps.scss',
            'web/static/lib/bootstrap/scss/_root.scss',
            'web/static/lib/bootstrap/scss/_grid.scss',
            'web/static/lib/bootstrap/scss/_tables.scss',
            'web/static/lib/bootstrap/scss/_images.scss',
            'web/static/lib/bootstrap/scss/_buttons.scss',
            'web/static/lib/bootstrap/scss/_alert.scss',
            'web/static/src/scss/functions.scss',
            'web/static/src/scss/utils.scss',
            ('include', 'web._assets_primary_variables'),
            ('include', 'web._assets_secondary_variables'),
            'web/static/src/libs/fontawesome/css/font-awesome.css',
            'web/static/src/scss/fontawesome_overridden.scss',
            'web/static/lib/odoo_ui_icons/*',
            'web/static/fonts/fonts.scss',
            'web/static/src/scss/pre_variables.scss',
            'web/static/src/webclient/actions/reports/bootstrap_review_report.scss',
            'web/static/src/webclient/actions/reports/report.scss',
            'accountant_knowledge/static/report/reports.scss',
        ],
    },
}
