{
    'name': 'Insilos Tenant Control',
    'version': '1.0',
    'category': 'Services',
    'summary': 'Tenant provisioning control plane',
    'author': 'Innoria',
    'depends': ['base', 'industry_templates', 'databases'],
    'data': [
        'security/tenant_control_security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'views/tenant_views.xml',
        'views/template_release_views.xml',
        'views/tenant_operation_views.xml',
        'views/search_views.xml',
        'views/workflow_kanban_views.xml',
        'views/databases_projection_views.xml',
        'views/tenant_control_menus.xml',
        'reports/is_tenant_report_actions.xml',
        'reports/is_tenant_report_templates.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
